version: "3.8"
services:
    mongodb:
      image: mongo
      container_name: mongodb-referencedata-service
      ports:
        - 27017:27017
      volumes:
        - data:/data
      environment:
        - MONGO_INITDB_ROOT_USERNAME=rootuser
        - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
      image: mongo-express
      container_name: mongo-express-referencedata-service
      restart: always
      ports:
        - 3000:8081
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
        - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
        - ME_CONFIG_MONGODB_SERVER=mongodb-referencedata-service
volumes:
  data: {}

networks:
  default:
    name: mongob_network